import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";

export default function Home() {
  return (
    <>
    <Head>
      <title>FYP2</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <section className="bg-dark-brown w-screen h-screen flex items-center justify-center">
      <div className='container mx-auto md:px-20'>
        <h1 className='font-bold text-7xl pb-12 text-center text-white'>WELCOME</h1>

        <Slide />

      </div>
    </section>
    </>
  )
}

function Slide() {
  return(
    <div className='grid md:grid-cols-2'>
      <div className='image'>
        <Image src={"/images/unitenlogo.png"} width={1000} height={600} />
      </div>
      <div className='info bg-amber'>
        <div className='cat'>
          <a className='text-dark-brown'>by IrfanKasram</a>
          <a className='text-dark-brown'>- Sem2 2022/2023</a>
        </div>
        <div className='title'>
          <a className='text-3xl md:text-6xl font-bold text-dark-brown'>Water Quality Monitoring System</a>
        </div>
        <div className='auth'>
          <p className='mb-2'>Existing admin?</p>
          <Link legacyBehavior href="/signIn">
            <a className='px-4 py-2 rounded-lg bg-blue-500 text-white font-semibold hover:bg-blue-600 transition duration-200'>Log in</a>
          </Link>
          <p className='mt-4 mb-2'>New admin?</p>
          <Link legacyBehavior href="/signUp">
            <a className='px-4 py-2 rounded-lg bg-gray-300 text-gray-800 font-semibold hover:bg-gray-400 transition duration-200'>Sign up</a>
          </Link>
        </div>
      </div>
    </div>
  )
}
